name: Optimizer

on:
  push:
    branches:
      - '*'
#  schedule:
#    - cron:  '0 * * * *'

jobs:
  optimization:
    runs-on: ubuntu-latest
    container:
      image: cyberbotics/webots:latest
    strategy:
      matrix:
        P_GAIN: [40, 42, 45, 47, 50, 60]
        I_GAIN: [90, 95, 100]
        D_GAIN: [0, 0.5, 1, 2.0, 3.0, 4.0, 5.0, 6.0, 10.0]
    steps:
    - uses: actions/checkout@v2
    - name: Compile Plugin
      run: |
        cd projects/plugins/physics/inverted_pendulum_perturbation
        make
    - name: Run Simulation
      run: |
        cd $GITHUB_WORKSPACE
        export P_GAIN=${{ matrix.P_GAIN }}
        export I_GAIN=${{ matrix.I_GAIN }}
        export D_GAIN=${{ matrix.D_GAIN }}
        xvfb-run webots --batch --mode=fast --stdout --stderr projects/worlds/inverted_pendulum.wbt
    - uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.P_GAIN }}-${{ matrix.I_GAIN }}-${{ matrix.D_GAIN }}
        path: projects/controllers/inverted_pendulum/*.txt
  analyze:
    needs: optimization
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: result
    - name: Analyze Data
      run: python analyzer.py
