name: Optimizer

on:
  push:
    branches:
      - '*'

jobs:
  optimization:
    runs-on: ubuntu-latest
    container:
      image: cyberbotics/webots:latest
    strategy:
      matrix:
        P_GAIN: [10, 20, 30, 40, 50]
        D_GAIN: [0, 1, 2, 3, 4]
    steps:
    - uses: actions/checkout@v2
    - name: Print Webots Version
      run: xvfb-run webots --version --batch
    - name: Print System Information
      run: xvfb-run webots --sysinfo --batch
    - name: Compile Plugin
      run: |
        cd projects/plugins/physics/inverted_pendulum_perturbation
        make
    - name: Run Simulation
      run: |
        cd $GITHUB_WORKSPACE
        xvfb-run webots --batch --mode=fast --stdout --stderr projects/worlds/inverted_pendulum.wbt
